my_first_blog/blog_writing/urls.py
from django.urls import path
from . import views

urlpatterns = [path('', views.PostView.as_view(), name='home'),
               path('<int:pk>/', views.PostDetail.as_view()),
               path('about_us', views.about_us, name='about'),
               path('create', views.create, name='create'),
               path('review/<int:pk>/', views.AddComments.as_view(), name='comments'),

               ]

my_first_blog/my_first_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog_writing.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

my_first_blog/blog_writing/models.py
from django.db import models


class Post(models.Model):
    ''' данные о постах'''
    title = models.CharField('Заголовок записи', max_length=100)
    description = models.TextField('Текст записи')
    author = models.CharField('Имя автора', max_length=100)
    date = models.DateField('Дата публикации')
    img = models.ImageField('Изображение', upload_to='image/%Y', null=True)

    def __str__(self):
        return f'{self.title}, {self.author}'

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'

class Comments(models.Model):
    '''Комментарии'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    post = models.ForeignKey(Post, verbose_name='Публикация', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.post}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

my_first_blog/blog_writing/forms.py
from .models import Post, Comments
from django.forms import ModelForm, TextInput, DateTimeInput, Textarea


class PostForms(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'author', 'date', 'img']

        widgets = {
            'title': TextInput(attrs={'class': 'form-control', 'placeholder': 'Заголовок записи'}),
            'description': Textarea(attrs={'class': 'form-control', 'placeholder': 'Текст статьи'}),
            'author': TextInput(attrs={'class': 'form-control', 'placeholder': 'Автор статьи'}),
            'date': DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'Дата публикации'}),
            # 'img': DateTimeInput(attrs={'class': 'form-control', 'placeholder': 'изображение'}),
        }

class CommentsForm(ModelForm):
    class Meta:
        model = Comments
        fields = ('name', 'email', 'text_comments')

my_first_blog/blog_writing/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from .models import Post
from .forms import PostForms, CommentsForm


class PostView(View):
    '''Вывод записей'''

    def get(self, request):
        posts = Post.objects.all()
        return render(request, 'blog/blog.html', {'post_list': posts})


class PostDetail(View):
    '''Вывод записей на отдельной странице'''

    def get(self, request, pk):
        post = Post.objects.get(id=pk)
        return render(request, 'blog/blog_detail.html', {'post': post})


class AddComments(View):
    '''Добавление комментариев'''

    def post(self, request, pk):
        form = CommentsForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post_id = pk
            form.save()
        return redirect(f'/{pk}')


def about_us(request):  # Вывод информации о нас
    return render(request, 'blog/about.html')


def create(request):
    error = ''
    if request.method == 'POST':
        form = PostForms(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('home')
        else:
            error = 'Форма неверное заполнена'

    form = PostForms()

    data = {
        'form': form,
        'error': error
    }

    return render(request, 'blog/create.html', data)

my_first_blog/templates/blog/about.html
{% load static %}
<html>
<head>
	<title> О нас </title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" type="text/css" media="all" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'css/side_panel.css' %}">
	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
	<aside>
		<img src="{% static 'css/img/logo.jpg' %}" width="100px" alt="Лого">
		<span class="logo"> Автоблог </span>
		<h3> Навигация </h3>
		<ul>
			<a href="{% url 'home' %}"><li><i class="bi bi-house-door-fill"></i> Главная </li></a>
			<a href="{% url 'about' %}"> <li><i class="bi bi-exclamation-circle"></i> О нас </li></a>
			<a href="/admin"> <li> <i class="bi bi-database-add"></i> Админ панель </li></a>
			<a href="{% url 'create' %}"> <li><button class="btn btn-info"><i class="bi bi-plus-square"></i> Добавить запись </button></li></a>
		</ul>
	</aside>

	<main>
		<h3>Краткая информация о нас</h3>
		<h4>Это мой первый опыт написания блога, прошу строго не судить</h4>
    </main>

my_first_blog/templates/blog/blog.html
{% load static %}
<html>
<head>
    <title>Главная страница</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
          type="text/css" media="all"/>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="{% static 'css/side_panel.css' %}">
    <link rel="shortcut icon" href="css/images/favicon.ico"/>

</head>
    <body>
        <aside>
            <img src="{% static 'css/img/logo.jpg' %}" width="100px" alt="Лого">
            <span class="logo"> Автоблог </span>
            <h3> Навигация </h3>
            <ul>
                <a href="{% url 'home' %}">
                    <li><i class="bi bi-house-door-fill"></i> Главная</li>
                </a>
                <a href="{% url 'about' %}">
                    <li><i class="bi bi-exclamation-circle"></i> О нас</li>
                </a>
                <a href="/admin">
                    <li><i class="bi bi-database-add"></i> Админ панель</li>
                </a>
                <a href="{% url 'create' %}">
                    <li>
                        <button class="btn btn-info"><i class="bi bi-plus-square"></i> Добавить запись</button>
                    </li>
                </a>
            </ul>
        </aside>

        <main>
            <h3>Записи</h3>
            {% for post in post_list %}
            <div>
                <div>
                    <a href="#"><img src="{{ post.img.url }}" width="200px"/></a>
                </div>
                <div>
                    <h4><a href="{{ post.id }}">{{ post.title }}</a></h4>
                    <p>{{ post.description }}</p>
                    <p>Автор: {{ post.author }} </p>
                </div>
                <div>&nbsp;</div>
            </div>
            {% endfor %}
        </main>

</body>
</html>

my_first_blog/templates/blog/blog_detail.html
{% load static %}
<html>
<head>
	<title>Главная страница</title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" type="text/css" media="all" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'css/side_panel.css' %}">
	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
	<aside>
		<img src="{% static 'css/img/logo.jpg' %}" width="100px" alt="Лого">
		<span class="logo"> Автоблог </span>
		<h3> Навигация </h3>
		<ul>
			<a href="{% url 'home' %}"><li><i class="bi bi-house-door-fill"></i> Главная </li></a>
			<a href="{% url 'about' %}"> <li><i class="bi bi-exclamation-circle"></i> О нас </li></a>
			<a href="/admin"> <li> <i class="bi bi-database-add"></i> Админ панель </li></a>
			<a href="{% url 'create' %}"> <li><button class="btn btn-info"><i class="bi bi-plus-square"></i> Добавить запись </button></li></a>
		</ul>
	</aside>

<div class="shell">
    <div class="border">

        <div id="main">
            <div id="content" class="left">

                <div class="projects">
                    <h3>{{ post.title }}</h3>
                    <p align="center">
                        <img src="{{ post.img.url }}" width="50%"/>
                    </p>
                    <div class="item">
                        <div class="text left">
                            <p>{{ post.description }}</p>
                            <p>Автор: {{ post.author }} </p>
                        </div>
                        <div class="cl">&nbsp;</div>
                    </div>
                </div>
            </div>

            <div class="fora-comment">
                <h3> Оставить комментарий </h3>
                <div>
                    <form action="{% url 'comments' post.id %}" method="post">
                        {% csrf_token %}
                        <div>
                            <label>Ваш комментарий</label>
                            <textarea name="text_comments"></textarea>
                        </div>
                        <div>
                            <label> Ваше имя *</label>
                            <input type="text" name="name">

                        </div>
                        <div>
                            <label> Ваше Email *</label>
                            <input type="email" name="email">
                        </div>

                        <div><input type="submit"></div>
                    </form>
                </div>
            </div>
            <div>
                {% for comment in post.comments_set.all %}
                <div class="view-comment">
                    <h5> {{ comment.name }}</h5>
                    <p>
                        {{ comment.text_comments }}
                    </p>
                </div>
                {% endfor %}
            </div>


            <div class="cl">&nbsp;</div>
        </div>


    </div>

    <div id="footer">
        <p class="copy right">Copyright &copy; 2022 </p>
    </div>
</div>
</body>
</html>

my_first_blog/templates/blog/create.html
{% load static %}
<html xmlns="http://www.w3.org/1999/html">
<head>
	<title> Добавление записи </title>
	<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" type="text/css" media="all" />
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.2/font/bootstrap-icons.css">
	<link rel="stylesheet" href="{% static 'css/side_panel.css' %}">
	<link rel="shortcut icon" href="css/images/favicon.ico" />

</head>
<body>
	<aside>
		<img src="{% static 'css/img/logo.jpg' %}" width="100px" alt="Лого">
		<span class="logo"> Автоблог </span>
		<h3> Навигация </h3>
		<ul>
			<a href="{% url 'home' %}"><li><i class="bi bi-house-door-fill"></i> Главная </li></a>
			<a href="{% url 'about' %}"> <li><i class="bi bi-exclamation-circle"></i> О нас </li></a>
			<a href="/admin"> <li> <i class="bi bi-database-add"></i> Админ панель </li></a>
			<a href="{% url 'create' %}"> <li><button class="btn btn-info"><i class="bi bi-plus-square"></i> Добавить запись </button></li></a>
		</ul>
	</aside>

	<main>
		<div class="features">
			<h1> Форма по добавлению статьи</h1>
			<form method="POST" enctype="multipart/form-data">
				{% csrf_token %}
				{{ form.title }}<br>
				{{ form.description }}<br>
				{{ form.author }}<br>
				{{ form.date }}<br>
				{{ form.img }}<br>
				<span>{{ error }}</span>
				<button class="btn btn-success" type="submit">Добавить заапись</button>
			</form>
		</div>
    </main>
</body>
</html>